Ready for code review
noomdalv/Building-with-Backgrounds-and-Gradients pull request #1
Opened 2019-07-22 17:40 UTC by noomdalv

Please review, thanks.

2019-07-23 01:01 UTC, mosaaleb commented
Currently reviewing

2019-07-23 01:25 UTC, mosaaleb requested changes
## Hi @noomdalv :wave:

### Amazing work so far :clap:. You have handled most of the requirements, yet there still some requirements needs be met.



### Main content links
- [ ] Each link is an `<a>` HTML tag, with a `<div>` tag inside it.
- [ ] The `<div>` tag  inside the `<a>` tag should use an image as background --  The text on the original page is actually an image

### Bottom images 
- [ ] is made of four `<a>` tags with `<div>` tags inside it.
- [ ] The `<div>`s inside the `<a>` tags should use an image as a background

### General
- [ ] Let's make sure that our style guidelines are ok by using [stickler](https://github.com/microverseinc/linters-config/tree/master/css). It's very easy to use, just follow the link.

**Also see my comment below**

Please submit a new code review once you finish these requirements.

#### Happy coding :computer:

2019-07-23 01:25 UTC, mosaaleb commented on index.html
> +          <div class="searchBar">
You can use an `<input>` tag without wrapping it with `<form>` tag for simple UI componenet like search bar. See [this](https://stackoverflow.com/questions/6483622/text-field-without-form?rq=1) for more information

2019-07-23 02:08 UTC, noomdalv commented
hey man thanks for the review,

gotta admit im confused because i thought the idea was to make the page as
similar as the original and the structure of my project is just as theirs
o_O

so here i am thinking if theres a list of these specific requirements for
each project? the odin project page just list some basic ones but thats
it.. not much regarding html structure :/
i was reading about stickler just now, because the only app to check for
errors on my last 3 projects has been w3c validator, maybe stickler is
listing these requirements?
im trying to install stickler and run it on my repo but i get
"We cannot generate a configuration file for the languages in this
repository. Please create a .stickler.yml".
am i doing it wrong? please help




El lun., 22 de jul. de 2019 a la(s) 20:25, Muhammad (
notifications@github.com) escribió:

> *@mosaaleb* requested changes on this pull request.
> Hi @noomdalv <https://github.com/noomdalv> 👋 Amazing work so far 👏. You
> have handled most of the requirements, yet there still some requirements
> needs be met. Main content links
>
>    - There should be three links
>    - Each link is an <a> HTML tag, with a <div> tag inside it.
>    - The <div> tag inside the <a> tag should use an image as background
>    -- The text on the original page is actually an image
>
> Bottom images
>
>    - is made of four <a> tags with <div> tags inside it.
>    - The <div>s inside the <a> tags should use an image as a background
>
> General
>
>    - Let's make sure that our style guidelines are ok by using stickler
>    <https://github.com/microverseinc/linters-config/tree/master/css>.
>    It's very easy to use, just follow the link.
>
> *Also see my comment below*
>
> Please submit a new code review once you finish these requirements.
> Happy coding 💻
> ------------------------------
>
> In index.html
> <https://github.com/noomdalv/Building-with-Backgrounds-and-Gradients/pull/1#discussion_r306093722>
> :
>
> > +
>
> +    <header>
>
> +      <nav>
>
> +        <ul id="navList">
>
> +          <li id="appleTab"><a href="#"><span></span></a></li>
>
> +          <li id="storeTab"><a href="#"><span></span></a></li>
>
> +          <li id="macTab"><a href="#"><span></span></a></li>
>
> +          <li id="ipodTab"><a href="#"><span></span></a></li>
>
> +          <li id="iphoneTab"><a href="#"><span></span></a></li>
>
> +          <li id="ipadTab"><a href="#"><span></span></a></li>
>
> +          <li id="iTunesTab"><a href="#"><span></span></a></li>
>
> +          <li id="supportTab"><a href="#"><span></span></a></li>
>
> +        </ul>
>
> +
>
> +        <div id="navSearch">
>
> +          <div class="searchBar">
>
>
> You can use an <input> tag without wrapping it with <form> tag for simple
> UI componenet like search bar. See this
> <https://stackoverflow.com/questions/6483622/text-field-without-form?rq=1>
> for more information
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/noomdalv/Building-with-Backgrounds-and-Gradients/pull/1?email_source=notifications&email_token=AMKWIWTWZONJXZXQEVDZBPTQAZMY7A5CNFSM4IF23ZZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB7GY7DI#pullrequestreview-265129869>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMKWIWWGHSOK6WDFYTYUQ4LQAZMY7ANCNFSM4IF23ZZA>
> .
>

2019-07-23 03:01 UTC, mosaaleb commented
Hi @noomdalv 
We have in Microverse a list for requirements written carefully for every project so that all the projects will have better html & css structure. Applying best practices is very important step in your learning journey.

Regarding stickler, we are using `style lint` in `.sticker.yml` file so that you have good style guidelines when writing css files. It does not though check for html files, but you can install html lint extension available in all text editors instead of using external validator. If you are using *vscode*, there is an extension called [htmllint](https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint), it will save you time when validating html files.

For the error part, have you created the `.stickler.yml` file in your project home directory?
All the instructions are explained in here [stickler](https://github.com/microverseinc/linters-config/tree/master/css)

Contact me on slack (Muhammad Ebeid) if anything is still unclear.

2019-07-24 20:10 UTC, Oghenebrume50 requested changes

2019-07-24 20:10 UTC, Oghenebrume50 commented on index.html
> +        <a href="#"><div class="btmImg bi4"></div></a>
Hi great work done so far, while everything is setup properly, this container overlaps to the bottom you have to make a little bit responsive. Do that and submit for re-review, kudos for a great start. And please check out Github flow, you should be using a feature brance not development branch. Anyways you can leave Github flow until your next project
![11](https://user-images.githubusercontent.com/37092867/61824948-2bb23d80-ae57-11e9-875b-5a8d93ba45e3.png)

2019-07-25 16:56 UTC, noomdalv commented on index.html
> +        <a href="#"><div class="btmImg bi4"></div></a>
done, imgs should have width percentages to resize accordingly

2019-07-26 18:11 UTC, samgaco commented
### Hi @noomdalv :hand: 

### Great job so far :+1: The website looks really nice. Still some points to address before giving you the approval:

* Correct the errors in the index file given to you by the https://validator.w3.org
* Enable a [focus effect](https://www.w3schools.com/cssref/sel_focus.asp) for the input tag of your search bar.
* For the text **_" Watch the "Your Verse" film and explore the stories"_** , that should be in text format and it should have a hover underline effect.
* Add a project description to the **readme file**, it is also suggested to add your contact and a live demo of the site. [Here](https://github.com/othneildrew/Best-README-Template) there is an example template for inspiration purposes.

### That would be it. Please :pray: address these changes and submit back for another code review.

2019-07-27 13:34 UTC, noomdalv commented
Hi, i went ahead an added the focus effect for the search input and the
main readme file was on master branch, so i just added a new one updated to
the pull request from development, there arent any wc3validator errors
showing for me, just warnings about headings.
i have an issue with this point:

   - For the text *" Watch the "Your Verse" film and explore the stories"* ,
   that should be in text format and it should have a hover underline effect.

Why? Because these are the project fixes/requirements that i have on my
first review from TSE *@mosaaleb*
Main content links

   -  There should be three links
   -  Each link is an <a> HTML tag, with a <div> tag inside it.
   -  The <div> tag inside the <a> tag should use an image as background --
   The text on the original page is actually an image

i sent him a msg regarding these suggestions and he said its microverse
specific requirements for the project, but now you tell me i need to put
text and not an image?
i dont understand why you guys are contradicting yourselves, please let me
know what should i do next so my project can be completed.


El vie., 26 de jul. de 2019 a la(s) 13:11, samgaco (notifications@github.com)
escribió:

> Hi @noomdalv <https://github.com/noomdalv> ✋ Great job so far 👍 The
> website looks really nice. Still some points to address before giving you
> the approval:
>
>    - Correct the errors in the index file given to you by the
>    https://validator.w3.org
>    - Enable a focus effect
>    <https://www.w3schools.com/cssref/sel_focus.asp> for the input tag of
>    your search bar.
>    - For the text *" Watch the "Your Verse" film and explore the stories"*
>    , that should be in text format and it should have a hover underline effect.
>    - Add a project description to the *readme file*, it is also suggested
>    to add your contact and a live demo of the site. Here
>    <https://github.com/othneildrew/Best-README-Template> there is an
>    example template for inspiration purposes.
>
> That would be it. Please 🙏 address these changes and submit back for
> another code review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/noomdalv/Building-with-Backgrounds-and-Gradients/pull/1?email_source=notifications&email_token=AMKWIWXILQI7UGVIO333KNLQBM433A5CNFSM4IF23ZZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25KSCQ#issuecomment-515549450>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMKWIWTI3UFEKAPYJ3XTKTLQBM433ANCNFSM4IF23ZZA>
> .
>

2019-07-27 13:52 UTC, Oghenebrume50 commented
Reviewing .......

2019-07-27 14:00 UTC, samgaco commented
@noomdalv  @Oghenebrume50  

Since I am quoted, I'd like to clarify my requirement; in the original website the first two texts are images, so @noomdalv  did well on that, but as it shows in the original website, the third one: **Watch the “Your Verse” film and explore the stories**, it's a text and it has a hoover underline effect. My intention was not to contradict Raphael's review, but I apologize to both anyway if it seemed like it.

I am sorry for the misunderstanding. Regards.

2019-07-27 19:33 UTC, noomdalv commented
Hello, i would like to object to this comment:
"the third one: *Watch the “Your Verse” film and explore the stories*, it's
a text and it has a hoover underline effect."

hmm not really, according to the original website
https://web.archive.org/web/20140301004610/http://www.apple.com/ every
"text" line you see on the main content its actually an <img>,
this specific image contains 2 versions of "*Watch the “Your Verse” film
and explore the stories*" , the first one has no underline and the second
has the underline, here's a snippet of said image:

[image: image.png]

and heres a snippet of the original html structure:

[image: image.png]


The way they achieve the underline effect its simply by positioning the
image with negative top margin when its hovered.

Its not my intention to disagree with your comments but to clarify
everything because my original project html structure was based on the same
as the original website but the first TSE told me i had to make changes
that werent explicitly listed, i complied with his suggestions and 2
reviews later im being told to change it again, so its really frustrating
to me because im just basically wasting time and losing motivation 😐.

Tbh now im just worried because i dont know if for the next code review i
will get another TSE and he will tell mesomething different, please
consider my position, thanks.

I added the underline effect as the original website and it should work
now, should i submit another code review form?







El sáb., 27 de jul. de 2019 a la(s) 09:00, samgaco (notifications@github.com)
escribió:

> @noomdalv <https://github.com/noomdalv> @Oghenebrume50
> <https://github.com/Oghenebrume50>
>
> Since I am quoted, I'd like to clarify my requirement; in the original
> website the first two texts are images, so @noomdalv
> <https://github.com/noomdalv> did well on that, but as it shows in the
> original website, the third one: *Watch the “Your Verse” film and explore
> the stories*, it's a text and it has a hoover underline effect. My
> intention was not to contradict Raphael's review, but I apologize to both
> anyway if it seemed like it.
>
> I am sorry for the misunderstanding. Regards.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/noomdalv/Building-with-Backgrounds-and-Gradients/pull/1?email_source=notifications&email_token=AMKWIWQO7FUPGAZS7IEKI5TQBRIGTA5CNFSM4IF23ZZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD26L7HQ#issuecomment-515686302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMKWIWVS3NYUBFJH6XXUDC3QBRIGTANCNFSM4IF23ZZA>
> .
>

2019-07-27 19:39 UTC, samgaco commented
Hi @noomdalv 

@Oghenebrume50 approved your project already in his last message. You are right, I apologize for my mistake. I am very sorry about it. Regards :+1:

2019-07-27 20:32 UTC, merged